<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * AlertGeneration
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertGeneration extends Base
{
    public function sendMessages($message,$type){
        $commonUserRepo =$this->getRepository('CommonUser');
        if($type->getType()=='All'){
            $mobileNumbers = $commonUserRepo->getAllNos();
        }elseif ($type->getType()=='Free Users'){
            $mobileNumbers = $commonUserRepo->getFreeNos();
        }elseif($type->getType()=='Package Users'){
            $mobileNumbers = $commonUserRepo->getAllPackageNos();
        }elseif($type->getType()=='Package A'){
            $mobileNumbers = $commonUserRepo->getPackageANos();
        }elseif($type->getType()=='Package B'){
            $mobileNumbers = $commonUserRepo->getPackageBNos();
        }elseif($type->getType()=='Package C'){
            $mobileNumbers = $commonUserRepo->getPackageCNos();
        }elseif($type->getType()=='Package D'){
            $mobileNumbers = $commonUserRepo->getPackageDNos();
        }

        return $mobileNumbers;

    }


}
