<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\True;

/**
 * CommonUserHistory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonUserHistory extends Base
{

    public function register($data, $user, $driver, $schedule, $todayDate){

        $date = new \DateTime($data->date);

        if($data->isCollected=="True"){
            $isCollected = True;
        }elseif ($data->isCollected=="False"){
            $isCollected = False;
        }

        $object=$this->getNewEntity();
        $object->setDate($date)
            ->setIsCollected($isCollected)
            ->setCommonUser($user)
            ->setDriver($driver)
            ->setSchedule($schedule)
        ;
        $em = $this->getEntityManager();
        $em->persist($object);
        $em->flush();
    }

    public function getHistoryFromUser($user){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.commonUser = :user')
            ->setParameter('user', $user)
        ;
        $result = $qb->getQuery()->getResult();
        return $result;
    }

    public function addNewRecord($todayDate,$user, $driver, $schedule){
        $date = new \DateTime($todayDate);

        $object=$this->getNewEntity();
        $object->setDate($date)
            ->setIsCollected(true)
            ->setCommonUser($user)
            ->setDriver($driver)
            ->setSchedule($schedule)
        ;
        $em = $this->getEntityManager();
        $em->persist($object);
        $em->flush();
    }

    public function getHistoryFromDateAndUser($data,$user){

        $date = new \DateTime($data->date);

        $qb = $this->createQueryBuilder('p');
        $qb->where('p.commonUser = :user')
            ->andWhere('p.date = :date')
            ->setParameter('user', $user)
            ->setParameter('date', $date)
        ;
        $result = $qb->getQuery()->getResult();
        return $result;
    }

}
