<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * CommonUserPackage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonUserPackage extends Base
{

    public function count(){
        $qb = $this->createQueryBuilder('p');
        $qb->select('count(p.id)');
        $result = $qb->getQuery()->getSingleScalarResult();
        return $result;
    }

    public function profile($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id = :id')
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }
}
