<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * DriverHistory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverHistory extends Base
{
    public function register($data,$driver,$schedule,$trackingUnit,$route){
        $date = new \DateTime($data->date);
        $startTime = new \DateTime($data->startTime);

        $object=$this->getNewEntity();
        $object->setStartTime($startTime)
            ->setDate($date)
            ->setDriver($driver)
            ->setRoute($route)
            ->setSchedule($schedule)
            ->setTrackingUnit($trackingUnit)
            ;

        $em = $this->getEntityManager();
        $em->persist($object);
        $em->flush();
    }

    public function getHistoryFromDriverScheduleDate($data,$driver,$schedule){
        $date = new \DateTime($data->date);

        $qb = $this->createQueryBuilder('p');
        $qb->where('p.date = :date')
            ->andWhere('p.driver = :driver')
            ->andWhere('p.schedule = :schedule')
            ->setParameter('date', $date)
            ->setParameter('driver', $driver)
            ->setParameter('schedule', $schedule)
        ;
        $result = $qb->getQuery()->getResult();
        return $result[sizeof($result)-1];

    }
}
