<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * DriverFeedback
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverFeedback extends Base
{
    public function profile($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id = :id')
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }


    public function register($request){

        $date = new \DateTime($request->date);
        $time = new \DateTime($request->time);

        $DriverRepo = $this->getRepository('Driver');
        $driver= $DriverRepo->profile($request->userId);

        $object=$this->getNewEntity();
        $object->setRate($request->rate)
            ->setFeedback($request->feedback)
            ->setDate($date)
            ->setTime($time)
            ->setDriver($driver)
        ;
        $em = $this->getEntityManager();
        $em->persist($object);
        $em->flush();
    }
}
