<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * IdeabizAccessCode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeabizAccessCode extends Base
{
    public function profile($metaCode){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.metaCode = :metaCode')
            ->setParameter('metaCode', $metaCode)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }
}
