<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * SmartBin
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartBin extends Base
{
    public function profile($serial){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.serial = :serial')
            ->setParameter('serial', $serial)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }
    public function getSmartBinFromId($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id = :id')
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }
}
