<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * SmartBinEvents
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartBinEvents extends EntityRepository
{
}
