<?php

namespace AppBundle\RepositoryORM;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingUnitLocate
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingUnitLocate extends Base
{
    public function getUnitLocate($truck){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.truck = :truck')
            ->setParameter('truck', $truck)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }

    public function profile($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id = :id')
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getSingleResult();
        return $result;
    }
}
